# Receivers
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4320
      http:
        endpoint: 0.0.0.0:4319

# Processors
processors:
  batch:
    timeout: 1s

# Exporters
exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    send_timestamps: true
    # This namespace will make some stupid changes
    # to the metric name so don't even bother.
    # namespace: promexample
    # QUESTION
    # This const labels will add some useless label data as well.
    # We can do this in the code, why here?
    # const_labels:
    #   label1: value1
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

extensions:
  health_check:
  pprof:
    endpoint: :1888
  # zpages:
  #   endpoint: :55679
      
# Pipelines
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
