version: '3'
services:
  otel-collector-gateway:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-config-gateway.yaml:/etc/otel/config-gateway.yaml
    command:
      - '--config=/etc/otel/config-gateway.yaml'
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # grpc
      - "4318:4318"   # http
      - "55670:55679" # zpages extension
    depends_on:
      - jaeger
      - loki
    networks:
      - loki
      - jaeger
  loki:
    image: grafana/loki:main
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
  jaeger:
    image: jaegertracing/jaeger:2.2.0
    # QUESTION: Why is this one disabled as well?
    # environment:
    #   - COLLECTOR_OTLP_ENABLED=true
    ports: 
    - 5775:5775 # QUESTION: These ports for what???
    - 6831:6831
    - 6832:6832
    - 5778:5778
    - 16686:16686 # For the UI.
    - 14268:14268
    - 14250:14250 # QUESTION: Why will this one be used and not the other non-16686?
    - 9411:9411   # For ingesting data from Zipkin?
    # - 4317:4317 # QUESTION: Why are these 2 disabled?
    # - 4318:4318 # QUESTION: Why are these 2 disabled?
    networks:
      - jaeger
networks:
    loki:
    jaeger:
